DROP TABLE IF EXISTS dbo.QRTZ_BLOB_TRIGGERS
GO

DROP TABLE IF EXISTS dbo.QRTZ_CALENDARS
GO

DROP TABLE IF EXISTS dbo.QRTZ_CRON_TRIGGERS
GO

DROP TABLE IF EXISTS dbo.QRTZ_FIRED_TRIGGERS
GO

DROP TABLE IF EXISTS dbo.QRTZ_LOCKS
GO

DROP TABLE IF EXISTS dbo.QRTZ_PAUSED_TRIGGER_GRPS
GO

DROP TABLE IF EXISTS dbo.QRTZ_SCHEDULER_STATE
GO

DROP TABLE IF EXISTS dbo.QRTZ_SIMPLE_TRIGGERS
GO

DROP TABLE IF EXISTS dbo.QRTZ_SIMPROP_TRIGGERS
GO

DROP TABLE IF EXISTS dbo.QRTZ_TRIGGERS
GO

DROP TABLE IF EXISTS dbo.QRTZ_JOB_DETAILS
  
GO